✨ Add `noClearScreen` flag
esbuild-kit/tsx pull request #23
Opened 2022-05-28 05:28 UTC by patheticGeek

When running in watch mode, sometimes the user doesn't want the console to be cleared, so added this flag.
Plz accept.

2022-05-28 12:55 UTC, privatenumber commented
Can you open an issue and explain your use-case?

2022-05-28 14:30 UTC, patheticGeek commented
> Can you open an issue and explain your use-case?

Here, #25

2022-06-10 14:49 UTC, knpwrs commented on src/watch.ts
> +			console.log('🔄 tsx: restarting');
It might be cool to make `noClearScreen` a boolean or string to provide a custom message here.

2022-06-10 21:53 UTC, privatenumber requested changes
Let's follow Vite's footsteps here: https://vitejs.dev/config/#clearscreen

Can you rename it to `clearScreen` and default it to `true`?

2022-06-11 08:24 UTC, patheticGeek commented
> Let's follow Vite's footsteps here: https://vitejs.dev/config/#clearscreen
> 
> Can you rename it to `clearScreen` and default it to `true`?

Yep will do it!

2022-06-11 08:33 UTC, patheticGeek commented
@privatenumber do you wanna change the message it logs?
Also gonna make it not log restarting on the first run cause thats start not a restart

2022-06-23 23:50 UTC, merged

2022-06-24 00:01 UTC, privatenumber commented
:tada: This PR is included in version 3.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/tsx/v/3.6.0)
- [GitHub release](https://github.com/esbuild-kit/tsx/releases/tag/v3.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-06-22 19:38 UTC, ccorcos commented
This flag doesn't appear in the `--help` documentation btw.